-- Korean Speller: Study Statistics
-- Run this once in Supabase SQL Editor.

create table if not exists public.study_activity (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    vocab_type text not null check (vocab_type in ('image', 'text')),
    vocab_id text not null,
    category text,
    korean text,
    english text,
    result text not null check (result in ('correct', 'wrong', 'skipped')),
    mode text not null default 'typing' check (mode in ('typing', 'multiple')),
    is_review boolean not null default false,
    created_at timestamptz not null default now()
);

create index if not exists study_activity_user_created_idx
on public.study_activity(user_id, created_at desc);

create index if not exists study_activity_user_category_idx
on public.study_activity(user_id, category);

alter table public.study_activity enable row level security;

drop policy if exists "Users can view their own study activity"
on public.study_activity;

create policy "Users can view their own study activity"
on public.study_activity
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own study activity"
on public.study_activity;

create policy "Users can insert their own study activity"
on public.study_activity
for insert
to authenticated
with check (auth.uid() = user_id);

create or replace function public.record_study_activity(
    p_vocab_type text,
    p_vocab_id text,
    p_category text,
    p_korean text,
    p_english text,
    p_result text,
    p_mode text default 'typing',
    p_is_review boolean default false
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
    if auth.uid() is null then
        raise exception 'Authentication required';
    end if;

    insert into public.study_activity (
        user_id,
        vocab_type,
        vocab_id,
        category,
        korean,
        english,
        result,
        mode,
        is_review
    )
    values (
        auth.uid(),
        p_vocab_type,
        p_vocab_id,
        nullif(p_category, ''),
        nullif(p_korean, ''),
        nullif(p_english, ''),
        p_result,
        coalesce(nullif(p_mode, ''), 'typing'),
        coalesce(p_is_review, false)
    );
end;
$$;

revoke all on function public.record_study_activity(text, text, text, text, text, text, text, boolean)
from public;

grant execute on function public.record_study_activity(text, text, text, text, text, text, text, boolean)
to authenticated;
