-- Mistake Review system
-- Run this in Supabase SQL Editor after the existing scalability/security SQL.

create table if not exists public.study_mistakes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  vocab_type text not null check (vocab_type in ('image', 'text')),
  vocab_id text not null,
  category text,
  korean text not null,
  english text,
  image text,
  wrong_count integer not null default 1,
  last_wrong_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, vocab_type, vocab_id)
);

alter table public.study_mistakes enable row level security;

drop policy if exists "Users can view their own mistakes" on public.study_mistakes;
create policy "Users can view their own mistakes"
on public.study_mistakes
for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can delete their own mistakes" on public.study_mistakes;
create policy "Users can delete their own mistakes"
on public.study_mistakes
for delete to authenticated
using (auth.uid() = user_id);

-- Vocabulary IDs in the existing image/text vocabulary tables are UUID strings.
-- Keep vocab_id as text so the mistake table can safely store UUID IDs (and remain
-- compatible if a future vocabulary source uses numeric IDs).
alter table public.study_mistakes
  alter column vocab_id type text using vocab_id::text;

-- Replace the old bigint RPC signature with the UUID/text-compatible signature.
drop function if exists public.record_study_mistake(text, bigint, text, text, text, text);

-- The website records mistakes through this function so wrong_count increments atomically.
create or replace function public.record_study_mistake(
  p_vocab_type text,
  p_vocab_id text,
  p_category text,
  p_korean text,
  p_english text default null,
  p_image text default null
)
returns public.study_mistakes
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.study_mistakes;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if p_vocab_type not in ('image', 'text') then
    raise exception 'Invalid vocabulary type';
  end if;

  insert into public.study_mistakes (
    user_id, vocab_type, vocab_id, category, korean, english, image,
    wrong_count, last_wrong_at, updated_at
  )
  values (
    auth.uid(), p_vocab_type, p_vocab_id, p_category, p_korean, p_english, p_image,
    1, now(), now()
  )
  on conflict (user_id, vocab_type, vocab_id)
  do update set
    category = excluded.category,
    korean = excluded.korean,
    english = excluded.english,
    image = excluded.image,
    wrong_count = public.study_mistakes.wrong_count + 1,
    last_wrong_at = now(),
    updated_at = now()
  returning * into result;

  return result;
end;
$$;

grant execute on function public.record_study_mistake(text, text, text, text, text, text) to authenticated;
