-- Korean Vocabs: Listening Practice v1
-- Run once in Supabase SQL Editor.

create table if not exists public.listening_questions (
  id bigint generated by default as identity primary key,
  category text not null default 'EPS-TOPIK',
  difficulty text not null default 'Beginner'
    check (difficulty in ('Beginner','Intermediate','Advanced')),
  question_text text not null,
  audio_text text not null,
  audio_url text,
  choice_1 text not null,
  choice_2 text not null,
  choice_3 text not null,
  choice_4 text not null,
  correct_answer smallint not null
    check (correct_answer between 1 and 4),
  translation text,
  explanation text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.listening_questions enable row level security;

drop policy if exists "Authenticated users can read active listening questions" on public.listening_questions;
create policy "Authenticated users can read active listening questions"
on public.listening_questions
for select
to authenticated
using (is_active = true);

-- Original practice questions. These are EPS-TOPIK-style, not copied official exam material.
insert into public.listening_questions
(category, difficulty, question_text, audio_text, choice_1, choice_2, choice_3, choice_4, correct_answer, translation, explanation)
values
('EPS-TOPIK','Beginner',
 '남자는 무엇을 하고 있습니까?',
 '남자는 지금 밥을 먹고 있습니다.',
 '밥을 먹습니다.','운동을 합니다.','책을 읽습니다.','잠을 잡니다.',
 1,'What is the man doing?','남자는 밥을 먹고 있습니다.'),
('EPS-TOPIK','Beginner',
 '여자는 어디에 갑니까?',
 '여자는 회사에 갑니다.',
 '학교','회사','병원','시장',
 2,'Where is the woman going?','여자는 회사에 갑니다.'),
('EPS-TOPIK','Beginner',
 '오늘 날씨가 어떻습니까?',
 '오늘은 날씨가 아주 좋습니다.',
 '비가 옵니다.','눈이 옵니다.','날씨가 좋습니다.','바람이 많이 붑니다.',
 3,'How is the weather today?','날씨가 아주 좋습니다.'),
('EPS-TOPIK','Beginner',
 '남자는 무엇을 삽니까?',
 '남자는 시장에서 사과를 삽니다.',
 '사과','우유','빵','책',
 1,'What does the man buy?','남자는 사과를 삽니다.'),
('EPS-TOPIK','Intermediate',
 '두 사람은 어디에서 만납니까?',
 '두 사람은 오후 세 시에 회사 앞에서 만납니다.',
 '학교 앞','회사 앞','식당 안','집 앞',
 2,'Where will the two people meet?','회사 앞에서 만납니다.')
on conflict do nothing;
